version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: "your_password"
      MYSQL_DATABASE: feedback_db
      MYSQL_USER: "your_username"
      MYSQL_PASSWORD: "your password"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  php:
    image: php:8.4-apache
    container_name: php_app
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    command: >
      bash -c "echo 'ServerName localhost' >> /etc/apache2/apache2.conf && 
               a2enmod rewrite &&
               apache2-foreground"

  frontend:
    image: nginx:latest
    container_name: frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro

volumes:
  db_data:
